version: "3.9" #Docker compose version number, it can vary based new version available.
services:
  joybuy_webservers:
    container_name: jb_webserver_container
    image: nginx:latest
    ports:
    - "80:80"

  joybuy_mysql_database:
    container_name: jb_mysql_container
    image: mysql:latest
    environment:
      MYSQL_USER: rajendra
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: joybuy
    ports:
      - "3306:3306" # this is port numbers used by mysql image
    volumes:
      - type: volume #this is the data volume which gets created while building the docker compose
        source: custom_volume
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: volume
        source: custom_volume
        target: /var/log/mysql # Log data
        volume:
          nocopy: true
    networks:
      - custom_network #this is the network volume which gets created while building the docker compose

  jb_invserv:
    container_name: jb_invserv_container
    ports:
      - "8080:8090"
    build: # path to the Dockerfile for the custom app
      context:  ./inventoryservice
      dockerfile: Dockerfile
    volumes: # mount the app's source code into the container
      - type: bind
        source: ./inventoryservice
        target: /app
    depends_on:
      - joybuy_mysql_database # make sure the databases service is started first
    networks:
      - custom_network
    env_file:
      - .env

  jb_salesserv:
    container_name: jb_salesserv_container
    ports:
      - "8081:8091"
    build: # path to the Dockerfile for the custom app
      context: ./salesservice
      dockerfile: Dockerfile
    volumes: # mount the app's source code into the container
      - type: bind
        source: ./salesservice
        target: /app
    depends_on:
      - joybuy_mysql_database # make sure the databases service is started first
      - jb_invserv # make sure the inventory service is started first
    networks:
      - custom_network
    env_file:
      - .env

  jb_paymserv:
    container_name: jb_paymserv_container
    ports:
      - "8082:8092"
    build: # path to the Dockerfile for the custom app
      context: ./paymentservice
      dockerfile: Dockerfile
    volumes: # mount the app's source code into the container
      - type: bind
        source: ./paymentservice
        target: /app
    depends_on:
      - joybuy_mysql_database # make sure the databases service is started first
      - jb_invserv # make sure the inventory service is started first
      - jb_salesserv # make sure the inventory service is started first
    networks:
      - custom_network
    env_file:
      - .env

#used to define named volumes and networks that can be shared by multiple services
volumes:
  custom_volume:
    name: jb_data
networks:
  custom_network:
    name: jb_network
